# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Ericson's blog
tagline:          'Time is limited, To be a better better man'
description:      'Hello! Here is my blog about technology and later about life.'
url:              http://ericsonyc.github.io

author:
  name:           'Ericson'
  url:            https://github.com/ericsonyc

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : ericson
