permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author:
  name: Ericson
  email: 1220246394@qq.com
  link: http://ericsonyc.github.io
  weibo:
  github: http://github.com/ericsonyc

# 站点信息
title: Ericson's Blog
description: Learn more and to be a better man
url: http://ericsonyc.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /public/img/Ericson.jpg
favicon: /public/img/SooHu.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: ericsonyc.github.io

# disqus 设置
disqus:
  shortname: eric
